book/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('isbn.urls')),
]

isbn/urls.py
from django.urls import path
from . import views

app_name = "isbn"

urlpatterns = [
               path('list/', views.BookListView.as_view(), name='book_list'),
               path('create/', views.SearchWordCreateView.as_view(), name='create'),
               path('create_done/', views.create_done, name='create_done'),
               path('word_list/', views.WordListView.as_view(), name='word_list'),
               path('update/<int:pk>/', views.WordUpdateView.as_view(), name='update'),
               path('update_done/', views.update_done, name='update_done'),
               path('delete/<int:pk>/', views.WordDeleteView.as_view(), name='delete'),
               path('delete_done/', views.delete_done, name='delete_done'),
               path('isbn_update/', views.update_isbn_info, name='isbn_update'),
]

isbn/models.py
from django.db import models
from django.utils import timezone


class SearchWord(models.Model):
    class Meta:
        verbose_name = '検索ワード'
        verbose_name_plural = '検索ワード'
                
    word = models.CharField(max_length=255)
    flag = models.BooleanField(verbose_name="有効フラグ", default=False)
    def __str__(self):
        return self.word


class Book(models.Model):
    class Meta:
        verbose_name = '書籍情報'
        verbose_name_plural = '書籍情報'
                
    word = models.ForeignKey(SearchWord, on_delete=models.PROTECT,verbose_name="検索ワード")
    isbn = models.BigIntegerField("書籍コード", unique=True)
    salesDate = models.DateField('発売日', default=timezone.now, blank=True, null=True)
    title = models.CharField("書籍タイトル",max_length=255)
    itemPrice = models.IntegerField("税込み価格",default=1, help_text="単位は円", blank=True, null=True)
    imageUrl = models.URLField("画像URL", blank=True, null=True)
    reviewAverage = models.FloatField("レビュー平均点",default=0, blank=True, null=True)
    reviewCount = models.IntegerField("レビュー件数",default=1, blank=True, null=True)
    itemUrl = models.URLField("商品URL", blank=True, null=True)
    def __str__(self):
        return self.title
# Create your models here.

isbn/forms.py
from django import forms
from .models import SearchWord
class SearchWordForm(forms.ModelForm):
    """
    新規データ登録画面用のフォーム定義
    """
    class Meta:
        model = SearchWord
        fields =['word','flag']

isbn/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from isbn.models import Book, SearchWord
from . forms import SearchWordForm
from django.urls import reverse_lazy
import subprocess

class BookListView(ListView):
    #利用するモデルを指定
    model = Book
    #データを渡すテンプレートファイルを指定
    template_name = 'isbn/isbn_list.html'
    #家計簿テーブルの全データを取得するメソッドを定義
    def queryset(self):
        return Book.objects.all()
# Create your views here.

class SearchWordCreateView(CreateView):
    
    #利用するモデルを指定
    model = SearchWord
    #利用するフォームクラス名を指定
    form_class = SearchWordForm
    #登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('isbn:create_done')

def create_done(request):
    #登録処理が正常終了した場合に呼ばれるテンプレートを指定
    return render(request, 'isbn/create_done.html')

class WordListView(ListView):
    #利用するモデルを指定
    model = SearchWord
    #データを渡すテンプレートファイルを指定
    template_name = 'isbn/searchword_list.html'
    #家計簿テーブルの全データを取得するメソッドを定義
    def queryset(self):
        return SearchWord.objects.all()

class WordUpdateView(UpdateView):
    
    #利用するモデルを指定
    model = SearchWord
    #利用するフォームクラス名を指定
    form_class = SearchWordForm
    #登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('isbn:update_done')


def update_done(request):
    #更新処理が正常終了した場合に呼ばれるテンプレートを指定
    return render(request, 'isbn/update_done.html')

class WordDeleteView(DeleteView):
    
    #利用するモデルを指定
    model = SearchWord
    #削除処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('isbn:delete_done')


def delete_done(request):
    return render(request, 'isbn/delete_done.html')

def update_isbn_info(request):
    """変数の初期化"""
    message = []
    rc_code = None
    if request.POST:
                
        cmd = 'python manage.py get_isbn_info'
        rc_code = subprocess.call(cmd, shell=True)

        if rc_code == 0:
            message = "楽天書籍情報の更新処理が正常終了しました。"
        else:
            message = "楽天書籍情報の更新処理が異常終了しました。"
    return render(request,'isbn/result.html',{
    "message": message,
    })

isbn/templates/isbn/base.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {# Bootstrap4を使う #}
  <!-- linkタグでbootstrapのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <!-- linkタグでDataTableのcssファイルを読み込む -->
  <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>

  <!-- タイトルの設定-->
  <title>書籍情報管理アプリ</title>

<body>

  {% block content %}

   <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->

  {% endblock %}

  <!-- bootstrapのjavascrit読み込み-->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <!-- DataTablesのjavascrit読み込み-->
  <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>


  <!-- Databableの定義-->
  <script>
  jQuery(function($){
    // デフォルトの設定を変更
    $.extend( $.fn.dataTable.defaults, {
        language: {
            url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
            }
            });
    $("#book_list").DataTable({
        "searching": true,     //検索機能
        "paging":   true,      //ページング機能
        "ordering": true,      //ソート機能
        "lengthChange": true,  //件数切り替え機能

        }).columns.adjust().draw();
        });
  </script>

</body>
</html>

isbn/templates/isbn/create_done.html
{% extends './base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'isbn:book_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">楽天書籍管理アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>楽天書籍管理アプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ登録が正常終了しました。</div>
{% endblock content %}

isbn/templates/isbn/delete_done.html
{% extends './base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'isbn:book_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">楽天書籍管理アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>楽天書籍管理アプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ削除が正常終了しました。</div>
{% endblock content %}

isbn/templates/isbn/isbn_list.html
<!-- 親テンプレートを読み込む-->
{% extends './base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'isbn:book_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">一覧表示</li>
       <li class="breadcrumb-item">
        <a href="{% url 'isbn:word_list' %}">検索ワード一覧</a>
       </li>
     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
          <h3><b>楽天書籍情報一覧</b></h3>
          
           <form action='{% url 'isbn:isbn_update' %}' method='POST' enctype="multipart/form-data">
             {% csrf_token %}

          <div class="btn-group">
          <input type="submit" class="btn btn-primary" value="更新" data-toggle="tooltip" data-placement="right"
           data-html="true">
          </div>
          </form>
         </div>
       <div class="card-body">
         <!-- テーブル表の定義 -->
         <table id=book_list width="100%" class="table table-striped table-bordered table-hover">
           　<!-- 表の列の定義-->
             <thead>
               <tr>
                 <th class="text-center">検索ワード</th>
                 <th class="text-center">書籍コード</th>
                 <th class="text-center">発売日</th>
                 <th class="text-center">タイトル</th>
                 <th class="text-center">イメージ画像</th>
                 <th class="text-center">値段</th>
                 <th class="text-center">レビュー平均点</th>
                 <th class="text-center">レビュー数</th>
               </tr>
             </thead>
           　<!-- ここまでが表の列の定義-->
           　<!-- 表のデータ部分の表示-->
             <tbody>
               {% for item in object_list %}
                 <tr class="odd gradeX text-center">
                   <td class="text-center" width="100">{{ item.word}}</td>
                   <td class="text-center" width="50">{{ item.isbn }}</td>
                   <td class="text-center" width="100">{{ item.salesDate }}</td>
                   <td class="text-center" width="140">{{ item.title }}</td>
                   <td class="text-center" width="50"><a href="{{item.itemUrl}}" target="_blank">
                     <img src="{{item.imageUrl}}" alt="{{ item.title }}"></a></td>
                   <td class="text-center" width="30">{{ item.itemPrice }}</td>
                   <td class="text-center" width="30">{{ item.reviewAverage }}</td>
                   <td class="text-center" width="30">{{ item.reviewCount }}</td>
                 </tr>
             {% endfor %}
             </tbody>
           　<!-- ここまでが表のデータ部分の表示-->
           </table>
           <!-- ここまでがテーブル表の定義 -->
      </div>
      </div>
   </div>
  </div>
<hr>

{% endblock content %}

isbn/templates/isbn/result.html
{% extends './base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'isbn:book_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">楽天書籍管理アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>楽天書籍管理アプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">{{message}}</div>
{% endblock content %}

isbn/templates/isbn/searchword_confirm_delete.html
{% extends './base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'isbn:book_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">楽天書籍管理アプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <h3>データ削除</h3></div>
       </div>
       <div class="content-wrapper">
         <div class="container-fluid">
           <p>{{ object }} のデータを削除していいですか?</p>

           <form method="post">
             <button class="btn btn-danger">削除する</button>
             {% csrf_token %}
           </form>
         </div>
       </div>
   </div>
 </div>
{% endblock %}

isbn/templates/isbn/searchword_form.html
{% extends './base.html' %}
{% load bootstrap %}
{% block content %}
  <form method="post">
    <div class="container">
      <div class="row">
        <div class="col-12">

          <div class="content-wrapper">
            <div class="container-fluid">
              <!-- Breadcrumbs-->
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="{% url 'isbn:book_list' %}">TOP</a>
                </li>
                <li class="breadcrumb-item active">楽天書籍管理アプリ</li>
                <li class="breadcrumb-item active">検索ワード登録</li>
              </ol>
              <!-- Example DataTables Card-->
              <div class="card mb-3">
                <div class="card-header">
                  <h3>検索ワード登録画面</h3></div>
                <div class="card-body">          {{ form|bootstrap }}
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <button class="btn btn-primary">保存</button>
        </div>
      </div>
    </div>
    {% csrf_token %}
  </form>
{% endblock %}

isbn/templates/isbn/searchword_list.html
<!-- 親テンプレートを読み込む-->
{% extends './base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'isbn:book_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">一覧表示</li>
       <li class="breadcrumb-item">
         <a href="{% url 'isbn:create' %}">新規登録</a>
       </li>
     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
          <h3><b>検索ワード一覧</b></h3></div>
       <div class="card-body">
         <!-- テーブル表の定義 -->
         <table id=book_list width="100%" class="table table-striped table-bordered table-hover">
           　<!-- 表の列の定義-->
             <thead>
               <tr>
                 <th class="text-center">検索ワード</th>
                 <th class="text-center">有効フラグ</th>
                 <th class="text-center">設定変更</th>
               </tr>
             </thead>
           　<!-- ここまでが表の列の定義-->
           　<!-- 表のデータ部分の表示-->
             <tbody>
               {% for item in object_list %}
                 <tr class="odd gradeX text-center">
                   <td class="text-center" width="100">{{ item.word}}</td>
                     {% if item.flag == False %}
                         <td class="text-center" width="50">無効</td>
                     {% endif %}
                     {% if item.flag == True %}
                   <td class="text-center" width="50">有効</td>
                     {% endif %}
              <td class="text-center" width="100">
                <a class="btn btn-primary" href="{% url 'isbn:update' item.pk %}" role="button">更新ページ</a>
                <a class="btn btn-danger" href="{% url 'isbn:delete' item.pk %}" role="button">削除ページ</a></td>
                 </tr>
             {% endfor %}
             </tbody>
           　<!-- ここまでが表のデータ部分の表示-->
           </table>
           <!-- ここまでがテーブル表の定義 -->
      </div>
      </div>
   </div>
  </div>
{% endblock content %}

isbn/templates/isbn/update_done.html
{% extends './base.html' %}
{% block content %}

  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'isbn:book_list' %}">TOP</a>
        </li>
        <li class="breadcrumb-item active">楽天書籍管理アプリ</li>
      </ol>
      <!-- Example DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-server"></i> <b>楽天書籍管理アプリ</b></div>
        <div class="card-body">

<div class="alert alert-info" role="alert">データ更新が正常終了しました。</div>
{% endblock content %}